
name: Ădotris
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up
        run: |
          git config --global user.name "levinhkhangzz"
          git config --global user.email "levinhkhang631@gmail.com"
      - name: Huy
        run: |
          while true; do
            for ((i=0; i<=1; i++)); do
              echo $i > Huy.txt
              git add .
              git commit -m "By Aedotris"
              git push origin main
            done
          done
