name: Auto Git Push

on:
  push:
    branches:
      - main  # chỉ định branch để trigger action

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.name "levinhkhangzz"
          git config --global user.email "levinhkhang631@gmail.com"

      - name: Commit and push changes
        env:
          GH_TOKEN: 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
        run: |
          git push origin main
